[package]
name = "eso-log-cliques"
version = "0.1.0"
edition = "2024"

[dependencies]
ctrlc = "3.4.7"
reqwest = { version = "0.12.22", features = ["json", "blocking"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
